// Real Google reviews for Хоум Офис Клийн / Home Office Clean.
// Source: https://www.google.com/maps?cid=14910716150916169460
//
// Generated by scripts/fetch-google-reviews.mjs — re-run that script to refresh.

import type {Testimonial} from './testimonials';

export const googleAggregate = {
  "rating": 4.3,
  "count": 16,
  "url": "https://www.google.com/maps?cid=14910716150916169460"
} as const;

export const googleReviews: readonly Testimonial[] = [
  {
    "name": "Пламена Спасова",
    "rating": 5,
    "date": "април 2025 г.",
    "text": "Много съм доволна от екипа. Основоното почистване на дома ми беше направено с много професионализъм, отношение и внимание към детайлите. Впечатли ме старанието, което влагаха в работата си. В същото време са организирани и експедитивни. Освен това са много любезни, внимателни и симпатични. Със сигурност това е най-добрата услуга, която съм ползвала до момента и отново ще се обръщам към тях, когато имам нужда. Благодаря от сърце!",
    "lang": "bg",
    "avatar": "/reviews/a43f8047e298.png"
  },
  {
    "name": "Пламена Спасова",
    "rating": 5,
    "date": "April 2025",
    "text": "I am very pleased with the team. The thorough cleaning of my home was done with great professionalism, attitude and attention to detail. I was impressed by the diligence they put into their work. At the same time, they are organized and expeditious. They are also very kind, attentive and sympathetic. This is certainly the best service I have used so far and I will turn to them again when I need it. Thank you from the bottom of my heart!",
    "lang": "en",
    "avatar": "/reviews/a43f8047e298.png"
  },
  {
    "name": "Tsoni Petrov",
    "rating": 5,
    "date": "април 2025 г.",
    "text": "Останах доволен от услугата им.  Отлично свършена работа, коректно отношение! Препоръчвам с две ръце! И най най важното е, че се справиха с котления камък по крановете!",
    "lang": "bg",
    "avatar": "/reviews/1ca4908a0753.png"
  },
  {
    "name": "Tsoni Petrov",
    "rating": 5,
    "date": "April 2025",
    "text": "I was satisfied with their service. Excellent job, correct attitude! I recommend it with both hands! And most importantly, they dealt with the scale on the taps!",
    "lang": "en",
    "avatar": "/reviews/1ca4908a0753.png"
  },
  {
    "name": "Nino Avreyski",
    "rating": 5,
    "date": "април 2025 г.",
    "text": "Работихме с тях за почистване след обзавеждане на нов апартамент. Доволни сме, бързо и качествено особено за прозорци. Пак бих ползвал услугите им.",
    "lang": "bg",
    "avatar": "/reviews/69384c9052ab.png"
  },
  {
    "name": "Nino Avreyski",
    "rating": 5,
    "date": "April 2025",
    "text": "We worked with them for cleaning after furnishing a new apartment. We are satisfied, fast and high quality especially for windows. I would use their services again.",
    "lang": "en",
    "avatar": "/reviews/69384c9052ab.png"
  },
  {
    "name": "Mina Kardakova",
    "rating": 5,
    "date": "март 2025 г.",
    "text": "Very pleased with the team !",
    "lang": "bg",
    "avatar": "/reviews/4412141bc345.png"
  },
  {
    "name": "Mina Kardakova",
    "rating": 5,
    "date": "March 2025",
    "text": "Very pleased with the team !",
    "lang": "en",
    "avatar": "/reviews/4412141bc345.png"
  }
];
