// Composition layer for the Testimonials section.
//
// - `googleReviews` is auto-generated by scripts/fetch-google-reviews.mjs from
//   the Google Places API (capped at 5 reviews per call by Google).
// - `manualReviews` is hand-curated from the Maps web UI to cover the reviews
//   the official API doesn't return.
//
// `testimonials` is the merged list rendered by the UI. Manual entries come
// first so newer hand-picked reviews show before older API-fetched ones.

import {googleReviews, googleAggregate} from './googleReviews';
import {manualReviews} from './manualReviews';

export type Testimonial = {
  name: string;
  rating: 1 | 2 | 3 | 4 | 5;
  date: string;
  text: string;
  lang: 'bg' | 'en';
  avatar?: string;
};

export {googleAggregate};

export const testimonials: readonly Testimonial[] = [...manualReviews, ...googleReviews];
